server:
  port: '8082'

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: 'true'

  h2:
    console:
      enable: 'true'

  flyway:
    username: sa
    password: ''



